### ISSUE TITLE
Bill of materials

### ISSUE THREAD

**Issue by oppiliappan** [MReavley/Slice36#1]
Would you happen to have a bill of materials for this build? I am looking to build the Slice36 up from scratch and a BOM would help greatly in assembly and orders, cheers!

**Comment by MReavley** [comment]
Hi, just added one to the Readme! You could probably edit the PCB to use SOD-123 diodes instead of the SOD-323 diodes I used, and also probably flip the orientation of D1-3, D13 and D16 to avoid trip-ups if you feel comfortable to do so. Otherwise, just note the orientation when you are soldering those in.

**Comment by oppiliappan** [comment]
Awesome, thanks for your work!
